[package]
name = "lightning-sys"
version = "0.2.3"
authors = ["Peter Elliott <pelliott@ualberta.ca>", "Darren Kulp <darren@kulp.ch>"]
edition = "2021"
license = "LGPL-3.0-or-later"
description = "GNU lightning bindings for rust"
readme = "README.md"
repository = "https://github.com/petelliott/lightning-sys"
documentation = "https://docs.rs/lightning-sys"

[dependencies]
lazy_static = "1.5"
tt-call = "1.0"

[build-dependencies]
bindgen = { version = "0.70.0", default-features = false, features = ["runtime"] }
cc = "1.0"

[dev-dependencies]
libc = "0.2"
